### ISSUE TITLE
Should we require use of Eve's SSO where login is required to use the tool?

### ISSUE THREAD

**Issue by cvweiss** [devfleet/awesome-eve#26]
This is merely here to prompt discussion and seek feedback. If one of the tools listed here require a login, should we require that the tool uses Eve Online's SSO? Some tools use default login/password, which could be considered a security risk.

Of course, not all tools will require a login.

**Comment by Ebag333** [comment]
if they don't, perhaps flag as a security risk.

**Comment by Kyria** [comment]
I don't believe that because an app use its own "login/password" that it's always a security risk (it might, for sure, but that's not 100% of them hopefully).

What could also be nice would be 2 "tags" (or whatever you want):
* `EVE SSO Login`
* `Custom Login`

This, to make the differences between both login systems, so people will know where they'll use their EVE Online login, and where they'll use a "custom" account they create, and thus making their own conclusion and choices about what they want / don't want to use.

**Comment by cvweiss** [comment]
Thank you both. I really like the flags idea. Allows us to keep our options open and yet distinguish the tools.

**Comment by cvweiss** [comment]
Closing issue, with XML going away eventually it won't really matter. Apps will adapt or be forgotten :)
